#!/usr/bin/env python3
"""
Build script for creating Dwellpy executable with PyInstaller.
Usage: python build.py
"""

import os
import sys
import shutil
import subprocess
import platform
from pathlib import Path

def clean_build():
    """Clean previous build artifacts."""
    print("🧹 Cleaning previous build artifacts...")
    
    # Directories to clean
    clean_dirs = ['build', 'dist', '__pycache__']
    
    for dir_name in clean_dirs:
        if os.path.exists(dir_name):
            shutil.rmtree(dir_name)
            print(f"   Removed: {dir_name}")
    
    # Clean .pyc files
    for root, dirs, files in os.walk('.'):
        for file in files:
            if file.endswith('.pyc'):
                os.remove(os.path.join(root, file))
        # Remove __pycache__ directories
        if '__pycache__' in dirs:
            shutil.rmtree(os.path.join(root, '__pycache__'))

def check_pyinstaller():
    """Check if PyInstaller is installed and accessible."""
    print("🔍 Checking PyInstaller...")
    
    # Method 1: Try to run pyinstaller --version directly
    try:
        result = subprocess.run(['pyinstaller', '--version'], 
                              capture_output=True, text=True, timeout=10)
        if result.returncode == 0:
            version = result.stdout.strip()
            print(f"   ✓ PyInstaller {version}")
            return True
        else:
            print("   ❌ PyInstaller command failed")
            print(f"   Error: {result.stderr}")
            return False
    except FileNotFoundError:
        print("   ❌ PyInstaller command not found")
        print("   Install with: pip install pyinstaller")
        return False
    except subprocess.TimeoutExpired:
        print("   ❌ PyInstaller command timed out")
        return False
    except Exception as e:
        print(f"   ❌ Error checking PyInstaller: {e}")
        return False

def check_dependencies():
    """Check if required dependencies are installed."""
    print("🔍 Checking Python dependencies...")
    
    required = ['PyQt6', 'pynput']
    missing = []
    
    for package in required:
        try:
            __import__(package)
            print(f"   ✓ {package}")
        except ImportError:
            missing.append(package)
            print(f"   ✗ {package}")
    
    if missing:
        print(f"\n❌ Missing dependencies: {', '.join(missing)}")
        print("Install with: pip install " + " ".join(missing))
        return False
    
    return True

def is_windows():
    """Check if running on Windows."""
    return platform.system().lower() == 'windows'

def create_spec_file():
    """Create the PyInstaller spec file if it doesn't exist."""
    spec_file = Path('dwellpy.spec')
    
    if not spec_file.exists():
        print("📝 Creating dwellpy.spec file...")
        
        # UAC flags only for Windows
        uac_flags = ""
        if is_windows():
            uac_flags = """    uac_admin=True,   # Request admin privileges (for mouse control)
    uac_uiaccess=True,"""
            print("   ✓ Adding Windows UAC flags for mouse control")
        else:
            print("   ✓ Skipping UAC flags (not Windows)")
        
        spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Dwellpy - Generated by build.py
Usage: pyinstaller dwellpy.spec
"""

import sys
from pathlib import Path

# Get the project root directory
project_root = Path.cwd()

# Analysis of the main script
a = Analysis(
    # Entry point - use the LAUNCHER script in project root
    ['launcher.py'],
    
    # Paths to search for modules
    pathex=[str(project_root)],
    
    # Binary files to include
    binaries=[],
    
    # Data files to include
    datas=[
        ('docs/README.md', 'docs'),
    ],
    
    # Hidden imports that PyInstaller might not detect
    hiddenimports=[
        'pynput',
        'pynput.mouse',
        'pynput.keyboard', 
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        # Include all your package modules explicitly
        'dwellpy',
        'dwellpy.main',
        'dwellpy.core',
        'dwellpy.core.dwell_algorithm',
        'dwellpy.core.click_manager', 
        'dwellpy.core.input_manager',
        'dwellpy.ui',
        'dwellpy.ui.ui_manager',
        'dwellpy.ui.window_manager',
        'dwellpy.ui.dialogs',
        'dwellpy.ui.dialogs.settings_dialog',
        'dwellpy.ui.dialogs.exit_dialog',
        'dwellpy.managers',
        'dwellpy.managers.button_manager',
        'dwellpy.managers.settings_manager',
        'dwellpy.managers.exit_manager',
        'dwellpy.config',
        'dwellpy.config.constants',
        'dwellpy.utils', 
        'dwellpy.utils.helpers',
        'dwellpy.__version__',
    ],
    
    # Packages to exclude (reduces size)
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'PIL',
        'cv2',
    ],
    
    # Additional options
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# Bundle everything
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# Create the executable - ONE FILE VERSION
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Dwellpy',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Set to True for debugging
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,{uac_flags}
)
'''
        
        with open(spec_file, 'w') as f:
            f.write(spec_content)
        
        print("   Created dwellpy.spec")
    else:
        print("📝 Using existing dwellpy.spec file...")

def check_launcher():
    """Check if launcher.py exists."""
    print("📄 Checking launcher.py...")
    
    launcher_file = Path('launcher.py')
    if launcher_file.exists():
        print("   ✓ launcher.py found")
        return True
    else:
        print("   ❌ launcher.py not found!")
        print("   Create launcher.py in the project root directory")
        return False

def build_executable():
    """Build the executable using PyInstaller."""
    print("🔨 Building executable...")
    
    try:
        # Run PyInstaller
        cmd = ['pyinstaller', '--clean', 'dwellpy.spec']
        
        print(f"   Running: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode == 0:
            print("   ✓ Build completed successfully!")
            return True
        else:
            print("   ❌ Build failed!")
            print(f"   Error: {result.stderr}")
            return False
            
    except subprocess.CalledProcessError as e:
        print(f"   ❌ Build failed: {e}")
        return False
    except FileNotFoundError:
        print("   ❌ PyInstaller command not found")
        return False

def test_executable():
    """Test if the built executable works."""
    print("🧪 Testing executable...")
    
    # Check different possible locations
    exe_paths = [
        Path('dist/Dwellpy.exe'),      # Windows one-file
        Path('dist/Dwellpy'),          # Linux/Mac one-file
        Path('dist/Dwellpy/Dwellpy.exe'),  # Windows one-dir
        Path('dist/Dwellpy/Dwellpy'),      # Linux/Mac one-dir
    ]
    
    exe_path = None
    for path in exe_paths:
        if path.exists():
            exe_path = path
            break
    
    if exe_path:
        print(f"   ✓ Executable found: {exe_path}")
        print(f"   📁 Size: {exe_path.stat().st_size / 1024 / 1024:.1f} MB")
        
        print("   🚀 You can test it by running:")
        print(f"      {exe_path.absolute()}")
        
        return True
    else:
        print("   ❌ Executable not found!")
        print("   Expected locations:")
        for path in exe_paths:
            print(f"      {path}")
        return False

def create_installer_info():
    """Create information about the build."""
    print("📋 Creating build information...")
    
    system_info = f"- System: {platform.system()} {platform.release()}"
    python_info = f"- Python: {platform.python_version()}"
    
    info_content = f"""# Dwellpy Build Information

## Executable Location
- **One-file build**: `dist/Dwellpy.exe` (Windows) or `dist/Dwellpy` (Linux/Mac)
- Ready to distribute - single file, no dependencies needed

## Distribution
1. Simply distribute the single executable file
2. Users run the .exe file directly
3. No Python installation required on target machine

## Features Included
- All Python dependencies bundled
- PyQt6 GUI framework  
- pynput mouse control library
- Application configuration and documentation

## Build Environment
{system_info}
{python_info}
- PyInstaller: Latest version
- Target: Single executable file

## Troubleshooting
- **Antivirus detection**: Some antivirus may flag PyInstaller executables as suspicious
- **Slow startup**: First run may take a few seconds to extract bundled files
- **Debugging**: Change `console=True` in dwellpy.spec and rebuild to see console output
- **UAC prompts**: {'Windows UAC enabled for mouse control access' if is_windows() else 'No UAC required (non-Windows)'}

## Usage
Double-click the executable to run Dwellpy. The application will create its settings file in the same directory as the executable.
"""
    
    with open('BUILD_INFO.md', 'w') as f:
        f.write(info_content)
    
    print("   Created BUILD_INFO.md")

def main():
    """Main build process."""
    print("🚀 Building Dwellpy Executable")
    print("=" * 40)
    
    # Show system info
    print(f"System: {platform.system()} {platform.release()}")
    print(f"Python: {platform.python_version()}")
    print()
    
    # Check we're in the right directory
    if not Path('dwellpy').exists():
        print("❌ Error: Run this script from the project root directory")
        print("   (where the 'dwellpy' folder is located)")
        sys.exit(1)
    
    # Build process
    steps = [
        ("Clean build artifacts", clean_build),
        ("Check PyInstaller", check_pyinstaller),
        ("Check Python dependencies", check_dependencies),
        ("Check launcher script", check_launcher),
        ("Create spec file", create_spec_file),
        ("Build executable", build_executable),
        ("Test executable", test_executable),
        ("Create build info", create_installer_info),
    ]
    
    for step_name, step_func in steps:
        print(f"\n📍 {step_name}")
        try:
            result = step_func()
            if result is False:  # Explicit False check
                print(f"❌ Step failed: {step_name}")
                sys.exit(1)
        except Exception as e:
            print(f"❌ Error in {step_name}: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)
    
    print("\n" + "=" * 40)
    print("🎉 Build completed successfully!")
    print(f"\n📦 Your executable is in: dist/")
    print("📋 See BUILD_INFO.md for distribution instructions")
    
    if is_windows():
        print("🔐 Windows UAC flags included for mouse control access")

if __name__ == "__main__":
    main()