# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Dwellpy - Generated by build.py
Usage: pyinstaller dwellpy.spec
"""

import sys
from pathlib import Path

# Get the project root directory
project_root = Path.cwd()

# Analysis of the main script
a = Analysis(
    # Entry point - use the LAUNCHER script in project root
    ['launcher.py'],
    
    # Paths to search for modules
    pathex=[str(project_root)],
    
    # Binary files to include
    binaries=[],
    
    # Data files to include
    datas=[
        ('dwellpy/assets', 'assets'),
        ('docs/README.md', 'docs'),
    ],
    
    # Hidden imports that PyInstaller might not detect
    hiddenimports=[
        'pynput',
        'pynput.mouse',
        'pynput.keyboard', 
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        # Include all your package modules explicitly
        'dwellpy',
        'dwellpy.main',
        'dwellpy.core',
        'dwellpy.core.dwell_algorithm',
        'dwellpy.core.click_manager', 
        'dwellpy.core.input_manager',
        'dwellpy.ui',
        'dwellpy.ui.ui_manager',
        'dwellpy.ui.window_manager',
        'dwellpy.ui.dialogs',
        'dwellpy.ui.dialogs.settings_dialog',
        'dwellpy.ui.dialogs.exit_dialog',
        'dwellpy.managers',
        'dwellpy.managers.button_manager',
        'dwellpy.managers.settings_manager',
        'dwellpy.managers.exit_manager',
        'dwellpy.config',
        'dwellpy.config.constants',
        'dwellpy.utils', 
        'dwellpy.utils.helpers',
        'dwellpy.__version__',
    ],
    
    # Packages to exclude (reduces size)
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'PIL',
        'cv2',
    ],
    
    # Additional options
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# Bundle everything
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# Create the executable - ONE FILE VERSION
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Dwellpy',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Set to True for debugging
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='dwellpy/assets/icons/Dwellpy.ico',

)
